export const NAVIGATIONS = [
  {
    name: 'Quickstart',
    path: '',
    children: [
      { name: 'Getting Started', path: 'docs/getting-started' },
      { name: 'Themes', path: 'docs/themes' },
      { name: 'Colors', path: 'docs/colors' },
      { name: 'Theme Generator', path: 'docs/theme-generator' },
      { name: 'Figma', path: 'docs/figma' },
      { name: 'ZapClass', path: 'docs/zapclass' },
      { name: 'Roadmap', path: 'docs/roadmap' },
      { name: 'Changelog', path: 'docs/changelog' },
    ],
  },
  {
    name: 'Components',
    path: '',
    children: [
      { name: 'Accordion', path: 'components/accordion' },
      { name: 'Alert', path: 'components/alert' },
      // { name: 'Aspect Ratio', path: 'components/aspect-ratio', type: 'Roadmap' },
      // { name: 'Avatar', path: 'components/avatar', type: 'Roadmap' },
      // { name: 'Autocomplete', path: 'components/autocomplete', type: 'Roadmap' },
      { name: 'Badge', path: 'components/badge' },
      // { name: 'Breadcrumb', path: 'components/breadcrumb', type: 'Roadmap' },
      { name: 'Button', path: 'components/button' },
      // { name: 'Card', path: 'components/card', type: 'Next' },
      // { name: 'Carousel', path: 'components/carousel', type: 'Roadmap' },
      { name: 'Checkbox', path: 'components/checkbox' },
      { name: 'Chip', path: 'components/chip' },
      { name: 'Date Picker', path: 'components/date-picker' },
      { name: 'Dialog', path: 'components/dialog' },
      { name: 'Dropdown menu', path: 'components/dropdown', type: 'Next' },
      // { name: 'File upload', path: 'components/file-upload', type: 'Roadmap' },
      // { name: 'Footer', path: 'components/footer', type: 'Roadmap' },
      // { name: 'Hover card', path: 'components/hover-card', type: 'Roadmap' },
      // { name: 'Header', path: 'components/header', type: 'Roadmap' },
      { name: 'Input', path: 'components/input' },
      // { name: 'Input OTP', path: 'components/input-otp', type: 'Roadmap' },
      { name: 'Modal', path: 'components/modal' },
      // {
      //   name: 'Navigation menu',
      //   path: 'components/navigation-menu',
      //   type: 'Roadmap',
      // },
      // { name: 'Pagination', path: 'components/pagination', type: 'Roadmap' },
      { name: 'Radio', path: 'components/radio' },
      { name: 'Select', path: 'components/select' },
      // { name: 'Separator', path: 'components/separator', type: 'Roadmap' },
      // { name: 'Sheet', path: 'components/sheet', type: 'Roadmap' },
      // { name: 'Slider', path: 'components/slider', type: 'Roadmap' },
      // { name: 'Snackbar', path: 'components/snackbar', type: 'Roadmap' },
      // { name: 'Spinner', path: 'components/spinner', type: 'Roadmap' },
      // { name: 'Sonner', path: 'components/sonner', type: 'Roadmap' },
      // { name: 'Table', path: 'components/table', type: 'Roadmap' },
      // { name: 'Tabs', path: 'components/tabs', type: 'Next' },
      { name: 'Textarea', path: 'components/textarea' },
      { name: 'Toast', path: 'components/toast' },
      { name: 'Toggle', path: 'components/toggle' },
      { name: 'Tooltip', path: 'components/tooltip' },
    ],
  },
];

export const NAVIGATIONS_MOBILE = [
  {
    name: 'Menu',
    path: '',
    children: [
      { name: 'Docs', path: 'docs/getting-started' },
      { name: 'Components', path: 'components/alert' },
      { name: 'Blog', path: 'contact' },
      { name: 'Examples', path: 'contact' },
      { name: 'Zap/AI', path: 'contact' },
      { name: 'Support', path: 'contact' },
    ],
  },
  ...NAVIGATIONS,
];
