name: Pre-PR Checks

on:
  pull_request:
    branches:
      - main
      - develop
      - features
      - releases

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Run Formatter
        run: npm run prettier:check

      - name: Run Linter
        run: npm run lint

      - name: Check for Build Errors on Library
        run: npm run build:lib

      - name: Send Status Check
        if: ${{ success() }}
        run: echo "All checks passed!"
